### ISSUE TITLE
Buttons' interactions feedback 

### ISSUE THREAD

**Issue by Dinoel27** [Volumetrics-io/mrjs#288] opened 2024-01-23 23:06 UTC
When pressing on a button to switch to another model the button bugs out and doesn't allow to load the model fast 
Results in making multiple clicks and no changes applied to the scene 

Have to hover out of the button region and hover back to click, after that the switching happens

**Comment by hanbollar** [comment] 2024-02-13 18:53
i think this was fixed in https://github.com/Volumetrics-io/mrjs/commit/791e8afb8641afb9e60c49d9a0609b0aa2d838c5

@Dinoel27 lmk if you're still experiencing this issue

otherwise this is good to close

**Comment by lobau** [comment] 2024-04-08 21:00
[this](https://github.com/Volumetrics-io/mrjs/issues/560) is actually the cause of the bug . It still happens. Let's use this bug https://github.com/Volumetrics-io/mrjs/issues/560 to track it

**Closed by lobau** 2024-04-08 21:00 UTC
